package com.entreprise.capita.entities;

public enum GOUVERNORAT {

    ARIANA, BEJA, BENAROUS, BIZERT, GABES, GAFSA, JANDOUBA, KAIROUAN, KASSERINE, KEBILI, LE_KEF, MAHDIA, LA_MANNOUBA, MEDENNINE, MONASTIR, NABEUL, SFAX, SIDI_BOUZID, SILIANA,
    SOUSSE, TATAOUINE, TOZUER, TUNIS, ZAGHOUANE
}
