  CREATE TABLE "PROFILE" 
   (	PROFILE VARCHAR2(10 ), 
	ID NUMBER(10)  PRIMARY key not null 
   ) ;
   
   insert into profile (profile, id) values ('PROD', 1);
   
     CREATE TABLE "ADDRESS" 
   (	"ID" NUMBER(19,0)  PRIMARY key not null ,
	"CITY" VARCHAR2(255 CHAR), 
	"COMMUNE" VARCHAR2(255 CHAR), 
	"COUNTRY" VARCHAR2(255 CHAR), 
	"DESCRIPTION" VARCHAR2(255 CHAR), 
	"GOUVERNORAT" VARCHAR2(255 CHAR), 
	"POSTAL_CODE" VARCHAR2(255 CHAR)
   ) ;
   
      CREATE TABLE "PRODUCT" 
   (	"ID" NUMBER(38,0)  PRIMARY key not null ,
	"NAME" VARCHAR2(255 BYTE), 
	"PRICE" FLOAT(126)
   ) ;
   
      SET DEFINE OFF;
Insert into PRODUCT (ID,NAME,PRICE) values ('2','CAP GAINER','50');
Insert into PRODUCT (ID,NAME,PRICE) values ('1','Whey BY CAPITA','250');

  CREATE TABLE "PROPERTY" 
   (	"ID" NUMBER(19,0)  PRIMARY key not null ,
	"CREATION_DATE" TIMESTAMP (6), 
	"DESCRIPTION" VARCHAR2(500 CHAR), 
	"PRICE" FLOAT(53), 
	"ROOMS" NUMBER(10,0), 
	"STATUS" VARCHAR2(255 CHAR), 
	"SURFACE" FLOAT(53), 
	"TITLE" VARCHAR2(255 CHAR), 
	"TRANSACTION_TYPE" VARCHAR2(255 CHAR), 
	"TYPE" VARCHAR2(255 CHAR), 
	"ADDRESS_ID" NUMBER(19,0)
   );
   
        CREATE TABLE "VOYAGEUR" 
   (	"ID" NUMBER(19,0)  PRIMARY key not null  ,
	"DATE_NAISSANCE" TIMESTAMP (6), 
	"EMAIL" VARCHAR2(255 CHAR), 
	"IDENTITY" VARCHAR2(255 CHAR), 
	"IS_IDENTITY_VERFIYED" NUMBER(1,0), 
	"LAST_NAME" VARCHAR2(255 CHAR), 
	"NAME" VARCHAR2(255 CHAR), 
	"PHOTO" BLOB, 
	"TELEPHONE" VARCHAR2(255 CHAR)
   );